USE DB_OPERACIONES;
GO
-- Tabla staging
CREATE TABLE registro_horas_stage(
UNIDAD VARCHAR(50),
JEFE VARCHAR(50),
AGENTE VARCHAR(50),
FECHA VARCHAR(50),
ACTIVO VARCHAR(50),
SS_HH DECIMAL(10,4),
ALMUERZO DECIMAL(10,4),
CAPACITACION DECIMAL(10,4),
RECREO DECIMAL(10,4),
URGENCIA DECIMAL(10,4),
OFF1 DECIMAL(10,4),
EVA1 DECIMAL(5,2),
EVA2 DECIMAL(5,2),
EVA3 DECIMAL(5,2),
EVA4 DECIMAL(5,2)
);
-- Carga desde CSV
BULK INSERT registro_horas_stage
FROM 'D:\BD_PROYECTO\REGISTRO_HORAS\registro_horas.csv'
WITH(
	FIRSTROW=2,
	FIELDTERMINATOR=';',
	ROWTERMINATOR='0x0d0a',
	CODEPAGE='65001',
	TABLOCK
);
--Paso a RAW
SET DATEFORMAT dmy;

INSERT INTO reporte_cliente_raw(
	agente,
	fecha,
	activo,
	baño,
	capacitacion,
	break_t,
	urgencia,
	off_t
)
SELECT
	AGENTE,
	TRY_CONVERT(DATE, LTRIM(RTRIM(FECHA))),
	ACTIVO,
	SS_HH,
	CAPACITACION,
	RECREO,
	URGENCIA,
	OFF1
FROM registro_horas_stage
WHERE TRY_CONVERT(DATE, LTRIM(RTRIM(FECHA))) IS NOT NULL;
